### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by xinanwan** [bchase1/myBikePlace#5]
# Design/Code Review 3

#### Reviewer: Xinan

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
||Which planned functionality has been met? |Add, get, update, and delete |
|| What planned functionality has not been met? |add delete and update buttons so users don't need ID to update or delete. When adding bikes for user, use getRemoteUser() so user don't need to enter userID|
||Describe the GitHub history and what it demonstrates about the project progress during the semester.|good amount of commits and nice progress history |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.|feedback all implemented |
||Other comments/notes?|add getByPropertyEqual() to genericDao |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.|good template. business logic is smooth. have good data validation on forms in JSP pages |
||Other comments/notes?| |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | Have good error reporting to user. good code quality in general  ||Other comments/notes?| |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy| logging properly used for debugging. ||Other comments/notes?| ||
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After
| good unit tests with perfect coverage |||Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| |
||Is it implemented correctly and working locally as well as on AWS?
| it is correctly implemented  |Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| OpenWeather API might want to stored separately rather than on the jsp page. might want to check with Paula about its complexity |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| Materialize|
||Is the independent research topic/technique implemented in the project?| yes |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?|yes |
||Is the hosted application fully functioning?| yes |
||Other comments/notes?| |

**Comment by bchase1** [comment]
Resolved all issues except left OpenWeatherMap api on home page after considering alternatives.
